'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PlusCircle, User, ChevronDown, Activity, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { LogWorkoutModal } from '@/components/dashboard/LogWorkoutModal';
import type { Player, WorkoutLog } from '@/types/domain';

async function fetchPlayersViaApi(): Promise<Player[]> {
  const res = await fetch('/api/players', { cache: 'no-store' });
  if (!res.ok) return [];
  const data = (await res.json()) as { players?: Player[] };
  return data.players ?? [];
}

interface DashboardWorkoutSectionProps {
  userId: string;
  initialAthletes: Player[];
}

// A new component to display the AI feedback
function AIFeedbackModal({
  isOpen,
  onClose,
  feedback,
  loading,
}: {
  isOpen: boolean;
  onClose: () => void;
  feedback: string | null;
  loading: boolean;
}) {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>AI Workout Feedback</DialogTitle>
          <DialogDescription>
            Here's some feedback on your workout, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {loading ? (
            <p>Generating feedback...</p>
          ) : (
            <p>{feedback}</p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// A new component to display the workout history
function WorkoutHistoryCard({
  workouts,
  onGetFeedback,
}: {
  workouts: WorkoutLog[];
  onGetFeedback: (workout: WorkoutLog) => void;
}) {
  return (
    <Card className='border-zinc-200'>
      <CardHeader>
        <CardTitle className='text-lg'>Recent Workouts</CardTitle>
      </CardHeader>
      <CardContent>
        {workouts.length === 0 ? (
          <p className='text-sm text-zinc-500'>No workouts logged yet.</p>
        ) : (
          <ul className='space-y-3'>
            {workouts.slice(0, 5).map((workout) => (
              <li key={workout.id} className='flex items-center justify-between p-3 bg-zinc-50 rounded-lg'>
                <div>
                  <p className='font-medium'>{workout.title}</p>
                  <p className='text-sm text-zinc-500'>
                    {workout.date.toLocaleDateString()} · {workout.duration} min
                  </p>
                </div>
                <Button
                  variant='outline'
                  size='sm'
                  onClick={() => onGetFeedback(workout)}
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Get AI Feedback
                </Button>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

export function DashboardWorkoutSection({ userId, initialAthletes }: DashboardWorkoutSectionProps) {
  const [isLogWorkoutModalOpen, setIsLogWorkoutModalOpen] = useState(false);
  const [selectedPlayerId, setSelectedPlayerId] = useState<string | null>(null);
  const [athletes, setAthletes] = useState<Player[]>(initialAthletes);
  const [workouts, setWorkouts] = useState<WorkoutLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAIFeedbackModalOpen, setIsAIFeedbackModalOpen] = useState(false);
  const [aiFeedback, setAIFeedback] = useState<string | null>(null);
  const [isAILoading, setIsAILoading] = useState(false);

  async function fetchWorkoutsViaApi(playerId: string) {
    try {
      const res = await fetch(`/api/players/${playerId}/dream-gym/workout-logs?limit=5`, {
        credentials: 'include',
      });
      if (!res.ok) return [];
      const data = await res.json();
      return (data.logs || []).map((log: any) => ({
        ...log,
        date: new Date(log.date || log.completedAt),
        completedAt: new Date(log.completedAt),
        createdAt: new Date(log.createdAt),
        updatedAt: new Date(log.updatedAt),
      })) as WorkoutLog[];
    } catch {
      return [];
    }
  }

  useEffect(() => {
    if (!userId) return;

    async function fetchData() {
      try {
        // If initialAthletes are not provided, fetch them via the API.
        if (initialAthletes.length === 0) {
          const fetchedAthletes = await fetchPlayersViaApi();
          setAthletes(fetchedAthletes);
        }

        if (athletes.length > 0) {
          // For simplicity, we'll fetch workouts for the first athlete
          const fetchedWorkouts = await fetchWorkoutsViaApi(athletes[0].id);
          setWorkouts(fetchedWorkouts);
        }
      } catch (error) {
        console.error("Failed to fetch dashboard data:", error);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [userId, initialAthletes, athletes.length]);

  const handleLogWorkoutClick = (playerId: string) => {
    setSelectedPlayerId(playerId);
    setIsLogWorkoutModalOpen(true);
  };

  const refreshWorkouts = async () => {
    if (userId && athletes.length > 0) {
      const fetchedWorkouts = await fetchWorkoutsViaApi(athletes[0].id);
      setWorkouts(fetchedWorkouts);
    }
  };

  const handleGetAIFeedback = async (workout: WorkoutLog) => {
    setIsAIFeedbackModalOpen(true);
    setIsAILoading(true);
    try {
      const response = await fetch('/api/ai/feedback', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ workout }),
      });
      const data = await response.json();
      if (data.success) {
        setAIFeedback(data.feedback);
      } else {
        setAIFeedback('Sorry, something went wrong.');
      }
    } catch (error) {
      setAIFeedback('Sorry, something went wrong.');
    } finally {
      setIsAILoading(false);
    }
  };

  return (
    <>
      {/* Quick Actions */}
      <Card className='border-zinc-200'>
        <CardHeader>
          <CardTitle className='text-lg'>Quick Actions</CardTitle>
        </CardHeader>
        <CardContent className='space-y-3'>
          {/* Log a Workout */}
          {athletes.length === 0 ? (
            <Button
              disabled
              className='w-full justify-start gap-3 h-12 bg-blue-800/50 cursor-not-allowed'
            >
              <Activity className='h-5 w-5' />
              <span className='font-medium'>Log Workout (Add athlete first)</span>
            </Button>
          ) : athletes.length === 1 ? (
            <Button
              onClick={() => handleLogWorkoutClick(athletes[0].id)}
              className='w-full justify-start gap-3 h-12 bg-blue-800 hover:bg-blue-700'
            >
              <Activity className='h-5 w-5' />
              <span className='font-medium'>Log Workout</span>
            </Button>
          ) : (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className='w-full justify-start gap-3 h-12 bg-blue-800 hover:bg-blue-700'>
                  <Activity className='h-5 w-5' />
                  <span className='font-medium'>Log Workout</span>
                  <ChevronDown className='h-4 w-4 ml-auto' />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align='start' className='w-[300px]'>
                <DropdownMenuLabel>Select Athlete</DropdownMenuLabel>
                <DropdownMenuSeparator />
                {athletes.map((athlete) => (
                  <DropdownMenuItem
                    key={athlete.id}
                    onClick={() => handleLogWorkoutClick(athlete.id)}
                    className='cursor-pointer'
                  >
                    <span>{athlete.name}</span>
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          )}
        </CardContent>
      </Card>

      {/* Workout History */}
      <WorkoutHistoryCard workouts={workouts} onGetFeedback={handleGetAIFeedback} />

      {selectedPlayerId && (
        <LogWorkoutModal
          isOpen={isLogWorkoutModalOpen}
          onClose={() => setIsLogWorkoutModalOpen(false)}
          onWorkoutLogged={refreshWorkouts}
          playerId={selectedPlayerId}
        />
      )}

      <AIFeedbackModal
        isOpen={isAIFeedbackModalOpen}
        onClose={() => setIsAIFeedbackModalOpen(false)}
        feedback={aiFeedback}
        loading={isAILoading}
      />
    </>
  );
}
